[[headers]]
  for = "/*"
    [headers.values]
    Content-Security-Policy = "default-src 'self' youtube-nocookie.com https://www.youtube-nocookie.com; script-src 'self' 'unsafe-inline' youtube-nocookie.com/ https://www.youtube-nocookie.com; style-src 'self' 'unsafe-inline'; img-src 'self' blob: data:; frame-src https://www.youtube-nocookie.com youtube-nocookie.com; connect-src 'self'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
